name: Edmonds Commerce CI
on: [push, pull_request]
env:
  envFile: '.env'
jobs:
  setup:
    name: Setup ENV Variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          script: |
            const core = require('@actions/core')
            const dotenv = require('dotenv')
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/actions/edmondscommerce/parseEnv.js`)
            console.log(script({core, dotenv}))

  test:
    needs: [setup]
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: testing
        id: tester
        run: |
          echo $TEST


