name: Edmonds Commerce CI
on: [push, pull_request]
jobs:
  setup:
    name: Setup ENV Variables
    runs-on: ubuntu-latest
    steps:
      - name: Read .env file
        id: dotenv
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          path: ./.env

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: testing
        if: $TEST === 'success'
        id: tester
        run: |
          echo $TEST


