name: Edmonds Commerce CI
on: [push, pull_request]
jobs:
  setup:
    name: Setup ENV Variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: /.env

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: testing
        id: tester
        run: |
          echo $TEST


